local_backend: true
backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

publish_mode: editorial_workflow

site_url: https://ironbark-jobs.com
logo_url: https://ironbark-jobs.com/assets/logo.png

collections:
  - name: "jobs"
    label: "Vacancies"
    folder: "jobs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Location", name: "location", widget: "string", required: false }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Requirements", name: "requirements", widget: "markdown", required: false }
      - { label: "Apply Form", name: "apply", widget: "hidden", default: "/form.html" }
